import type {Metadata} from "next"
import "./globals.css"
import {Roboto} from "next/font/google"
import SideNavbar from "@/components/SideNavbar"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SideNavbar />
      <body className={`${roboto.className} bg-gray-100`}>{children}</body>
    </html>
  )
}
