let students: IStudents[] = [
  {
    id: 31211,
    fullName: "Qobiljon Sulaymonov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 11,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31212,
    fullName: "Islomjon Tursunaliyev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 12,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31213,
    fullName: "Hushnudbek Ravshanov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 13,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31214,
    fullName: "Abdulatifjon Ahmadjonov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 14,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31215,
    fullName: "Rahmatillo Raxmonaliyev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 15,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31216,
    fullName: "Begzodjon Bo'riboyev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 16,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31217,
    fullName: "Amirxon Murodov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Kotlin",
    phone: "+998 91 311 52 43",
    userPercentage: 17,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31218,
    fullName: "Bexruzbek Baxtiyorjonov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Kotlin",
    phone: "+998 91 311 52 43",
    userPercentage: 18,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31219,
    fullName: "Islomjon Abdusalomov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Kotlin",
    phone: "+998 91 311 52 43",
    userPercentage: 19,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31220,
    fullName: "Boburjon Maxmudov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 20,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31221,
    fullName: "Jasurbek Marufov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 21,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31222,
    fullName: "Muhammadqodir Syfiddinov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 22,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31223,
    fullName: "Javlonbek Anvarov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 23,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31224,
    fullName: "Javohir Qodirjonov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 24,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31225,
    fullName: "Azizhon Saminjonov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 25,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31226,
    fullName: "Husniddin Muxtorov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 26,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31227,
    fullName: "Damir Muhammadov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 27,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31228,
    fullName: "Mirziyo Isroilov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 28,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31229,
    fullName: "Ulug'bek Muhammadiyev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 29,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31230,
    fullName: "Islomjon Abdusattorov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 30,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31231,
    fullName: "Salohiddin Sirojiddinov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 31,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31232,
    fullName: "Behruzbek Sharofiddinov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 32,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31233,
    fullName: "Shamshodbek Raxmataliyev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 33,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31234,
    fullName: "Islomjon Meliqo'ziyev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 34,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31235,
    fullName: "Malikaxon Meliqo'ziyev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 35,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31236,
    fullName: "Boburjon Akramjonov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Python",
    phone: "+998 91 311 52 43",
    userPercentage: 36,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31237,
    fullName: "Rashidxon Kabirov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Frontend",
    phone: "+998 91 311 52 43",
    userPercentage: 37,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31238,
    fullName: "Azizjon Qoldashev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Frontend",
    phone: "+998 91 311 52 43",
    userPercentage: 38,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31239,
    fullName: "Saloxiddin Muxtorov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Frontend",
    phone: "+998 91 311 52 43",
    userPercentage: 39,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31240,
    fullName: "Muhammadrizo Anvarov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Frontend",
    phone: "+998 91 311 52 43",
    userPercentage: 40,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31241,
    fullName: "Madinaxon Inomova",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Literacy",
    phone: "+998 91 311 52 43",
    userPercentage: 41,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31242,
    fullName: "Abubakr Anvarov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Android",
    phone: "+998 91 311 52 43",
    userPercentage: 42,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31243,
    fullName: "Boburjon Raxmonov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Literacy",
    phone: "+998 91 311 52 43",
    userPercentage: 43,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31244,
    fullName: "Muhammdrizo Yo'ldashev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Literacy",
    phone: "+998 91 311 52 43",
    userPercentage: 44,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31245,
    fullName: "Umidjon Eshonboyev",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Literacy",
    phone: "+998 91 311 52 43",
    userPercentage: 45,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31246,
    fullName: "Gavharoy Meliboyeva",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Literacy",
    phone: "+998 91 311 52 43",
    userPercentage: 46,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
  {
    id: 31247,
    fullName: "Bexruzbek Raxmonov",
    birthday: "May 10, 2024",
    address: "Beshkapa",
    group: "Literacy",
    phone: "+998 91 311 52 43",
    userPercentage: 47,
    userPhoto: "https://mighty.tools/mockmind-api/content/human/65.jpg",
  },
]

export const getStudents = () => students
export const addStudents = (student: IStudents) => {
  students.push(student)
}
export const deleteStudents = (id: number) => {
  students = students.filter((student) => student.id !== id)
}
export const updateStudents = (
  id: number,
  fullName: string,
  birthday: string,
  address: string,
  group: string,
  phone: string,
  userPhoto: string,
  userPercentage: number
) => {
  const student = students.find((student) => student.id === id)

  if (student) {
    student.address = address
    student.birthday = birthday
    student.fullName = fullName
    student.group = group
    student.phone = phone
    student.userPercentage = userPercentage
    student.userPhoto = userPhoto
  } else {
    throw new Error("NO STUDENT FOUND")
  }
}

export const getById = (id: number) => {
  return students.find((student) => student.id === id)
}
